freeze("$(PORT_DIR)/modules")
require("bundle-networking")
require("dht")
require("ds18x20")
require("neopixel")
require("onewire")
require("aioespnow")
package("primitives", base_path="$(MPY_DIR)/lib/micropython-async/v3")
package("threadsafe", base_path="$(MPY_DIR)/lib/micropython-async/v3")
